# Generated by Django 6.0.3 on 2026-10-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_paypear_payment_api'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fragmenttransaction',
            index=models.Index(fields=['id_from_payment_api'], name='fragment_tx_payment_id'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='transaction_status_created'),
        ),
    ]
