from __future__ import annotations

import logging
import random
from collections.abc import Awaitable
from decimal import Decimal
from dishka import FromDishka
from telegram import InputMediaPhoto, Message
from telegram.error import BadRequest, NetworkError, RetryAfter, TimedOut
from telegram.ext import ExtBot
from typing import cast, overload, TypeVar, ParamSpec
from uuid import UUID

from bot.renderers.base import create_media_source
from bot.renderers.webhook import get_message_parts_for_status
from core.domain.enums import TransactionStatus
from core.domain.network_utils import SAFE_TO_RETRY, RetriesEntity, get_timeout_error_or_none
from core.domain.schemas.payment import PaymentPayloadDict
from core.integrations.fragment.enums import FragmentStatus
from core.integrations.fragment.errors import (
    FragmentAPINetworkError,
    FragmentAPINotEnoughBalanceError,
    FragmentAPITemporaryError,
    FragmentAPITooManyRequests
)
from core.integrations.fragment.schemas import SendStarsResponse
from core.ioc import inject
from core.models import Transaction
from core.repositories.utils import safe_db_action_async_with_retries_celery
from core.services.payment import PaymentService
from core.services.support import SupportService
from core.services.transaction import TransactionService
from core.tasks import Task

logger = logging.getLogger(__name__)


P = ParamSpec("P")
R = TypeVar("R")
TR = TypeVar("TR")
CR = TypeVar("CR")


@overload
async def unsafe_get_support_url() -> str: ... # noqa  # pyright: ignore[reportInconsistentOverload]


@inject
async def unsafe_get_support_url(*, support_service: FromDishka[SupportService]) -> str:
    return await support_service.get_support_url()


@overload
async def unsafe_get_transaction(  # noqa  # pyright: ignore[reportInconsistentOverload]
        transaction_id: UUID,
        is_select_user: bool = True,
        is_select_metadata: bool = True
) -> Transaction | None: ...


@inject
async def unsafe_get_transaction(
        transaction_id: UUID,
        is_select_user: bool = True,
        is_select_metadata: bool = True,
        *,
        trans_service: FromDishka[TransactionService]
) -> Transaction | None:
    return await trans_service.get_transaction(transaction_id, is_select_user, is_select_metadata)


@overload
async def safe_create_transaction_with_retries(  # noqa  # pyright: ignore[reportInconsistentOverload]
        celery_task: Task[P,R], started_at: float, celery_kwargs: dict[str, object], timeout: float,
        transaction_id: UUID,
        status: TransactionStatus, parsed_payload: PaymentPayloadDict, payment_method: str
) -> Transaction | None: ...


@inject
async def safe_create_transaction_with_retries(
        celery_task: Task[P,R], started_at: float, celery_kwargs: dict[str, object], timeout: float,
        transaction_id: UUID,
        status: TransactionStatus, parsed_payload: PaymentPayloadDict, payment_method: str,
        *,
        trans_service: FromDishka[TransactionService]
) -> Transaction | None:
    transaction = await safe_db_action_async_with_retries_celery(
        trans_service.create_transaction(
            transaction_id,
            parsed_payload, payment_method,
            status, payload={"autogenerated": (
                "Это автоматически сгенерированная транзакция из вебхука, "
                "так как исходная транзакция была удалена"
            )}
        ),
        celery_task, started_at, celery_kwargs, timeout,
        str(transaction_id)
    )
    return transaction


async def safe_get_support_url_with_retries(
        celery_task: Task[P,R], started_at: float, celery_kwargs: dict[str, object], timeout: float,
        transaction_id: str
) -> str:
    support_url = await safe_db_action_async_with_retries_celery(
        unsafe_get_support_url(),
        celery_task, started_at, celery_kwargs, timeout,
        transaction_id
    )

    if support_url is None:
        support_url = "https://t.me/pmlame"  # fallback

    return support_url


async def safe_get_transaction_with_retries(
        celery_task: Task[P,R], started_at: float, celery_kwargs: dict[str, object], timeout: float,
        transaction_id: UUID,
        *,
        is_select_user: bool = True,
        is_select_metadata: bool = True
) -> Transaction | None:
    """
    Рано или поздно получит транзакцию. Если не получится её найти, или произойдёт тайм-аут, то вернётся `None`
    """
    return await safe_db_action_async_with_retries_celery(
        unsafe_get_transaction(transaction_id, is_select_user, is_select_metadata),
        celery_task, started_at, celery_kwargs, timeout,
        str(transaction_id)
    )


@overload
async def safe_set_status_for_transaction_obj_with_retries(  # noqa  # pyright: ignore[reportInconsistentOverload]
        celery_task: Task[P,R], started_at: float, celery_kwargs: dict[str, object], timeout: float,
        transaction: Transaction, new_status: TransactionStatus
) -> tuple[bool, Transaction]: ...


@inject
async def safe_set_status_for_transaction_obj_with_retries(
        celery_task: Task[P,R], started_at: float, celery_kwargs: dict[str, object], timeout: float,
        transaction: Transaction, new_status: TransactionStatus,
        *,
        trans_service: FromDishka[TransactionService]
) -> tuple[bool, Transaction]:
    """
    - Если предыдущий статус уже был `new_status`, вернётся `(False, transaction)`

    - В случае тайм-аута будет автоматический перезапуск таски

    - Если был тайм-аут при попытке обновить статус в БД, вернётся `(False, transaction)`

    - В случае успеха возвращается `(True, updated_transaction)`
    """

    if transaction.status == new_status:
        return False, transaction

    updated_transaction = await safe_db_action_async_with_retries_celery(
        trans_service.update_by_obj(transaction, new_status=new_status, is_count_metadata=False),
        celery_task, started_at, celery_kwargs, timeout,
        str(transaction.id)
    )

    if updated_transaction is None:
        return False, transaction

    return updated_transaction


@overload
async def safe_set_status_for_transaction_id_with_retries(  # noqa  # pyright: ignore[reportInconsistentOverload]
        celery_task: Task[P,R], started_at: float, celery_kwargs: dict[str, object], timeout: float,
        transaction_id: UUID, new_status: TransactionStatus
) -> bool: ...


@inject
async def safe_set_status_for_transaction_id_with_retries(
        celery_task: Task[P,R], started_at: float, celery_kwargs: dict[str, object], timeout: float,
        transaction_id: UUID, new_status: TransactionStatus,
        *,
        trans_service: FromDishka[TransactionService]
) -> bool:
    is_changed = await safe_db_action_async_with_retries_celery(
        trans_service.update_by_id(transaction_id, new_status=new_status, is_count_metadata=False),
        celery_task, started_at, celery_kwargs, timeout,
        str(transaction_id)
    )

    return False if is_changed is None else is_changed


@overload
async def safe_update_transaction_payload_with_retries(  # noqa  # pyright: ignore[reportInconsistentOverload]
        celery_task: Task[P,R], started_at: float, celery_kwargs: dict[str, object], timeout: float,
        transaction: Transaction, new_payload: dict[str, object]
) -> tuple[bool, Transaction] | None: ...


@inject
async def safe_update_transaction_payload_with_retries(
        celery_task: Task[P,R], started_at: float, celery_kwargs: dict[str, object], timeout: float,
        transaction: Transaction, new_payload: dict[str, object],
        *,
        trans_service: FromDishka[TransactionService]
) -> tuple[bool, Transaction] | None:
    return await safe_db_action_async_with_retries_celery(
        trans_service.update_by_obj(transaction, new_payload=new_payload, is_count_transaction=False),
        celery_task, started_at, celery_kwargs, timeout,
        str(transaction.id)
    )


@overload
async def create_fragment_transaction_if_not_sent_with_retries(  # noqa  # pyright: ignore[reportInconsistentOverload]
        celery_task: Task[P,R], started_at: float, celery_kwargs: dict[str, object], timeout: float,
        transaction: Transaction
) -> tuple[SendStarsResponse, str]: ...


@inject
async def create_fragment_transaction_if_not_sent_with_retries(
        celery_task: Task[P,R], started_at: float, celery_kwargs: dict[str, object], timeout: float,
        transaction: Transaction,
        *,
        payment_service: FromDishka[PaymentService]
) -> tuple[SendStarsResponse, str]:
    """
    При ошибке возвращает текст ошибки вторым аргументом.

    Если полученный статус финальный, то первым аргументом будет соответствующий `TransactionStatus`, иначе `None`.

    Если первый аргумент `TransactionStatus.FAILED`, то вторым аргументом всегда будет текст ошибки.
    """

    try:
        timeout_err = get_timeout_error_or_none(
            RetriesEntity.NETWORK_TIME, started_at, timeout,
            f"{payment_service.create_fragment_transaction.__qualname__}"
        )
        if timeout_err is not None:
            raise timeout_err

        try:
            response_or_transaction: SendStarsResponse | Transaction = await payment_service.create_fragment_transaction(
                transaction,
                timeout=45.0,
                recreate=False
            )

        except FragmentAPINetworkError as exc:
            raise celery_task.retry(
                exc=exc,
                countdown=5.0 + random.uniform(0.0, 3.0),
                kwargs=celery_kwargs
            )

        except FragmentAPITooManyRequests as exc:
            retry_after = exc.retry_after
            if retry_after is None:
                retry_after = 60.0

            raise celery_task.retry(
                exc=exc,
                countdown=float(retry_after) + random.uniform(0.0, 1.0),
                kwargs=celery_kwargs
            )

        except (FragmentAPITemporaryError, FragmentAPINotEnoughBalanceError) as exc:
            raise celery_task.retry(
                exc=exc,
                countdown=60.0 + random.uniform(0.0, 10.0),
                kwargs=celery_kwargs
            )

        except Exception as exc:
            logger.exception(f"{exc.__class__.__name__} - {str(exc)}")
            raise exc

        if isinstance(response_or_transaction, Transaction):
            err_msg = f"Попытка отправки звёзд по транзакции {response_or_transaction.id} уже была"
            exc = RuntimeError(err_msg)
            logger.exception(f"{exc.__class__.__name__} - {str(exc)}")
            raise exc

        response = response_or_transaction

        status = cast(FragmentStatus, response["status"])

        if status in (
                FragmentStatus.CREATED, FragmentStatus.PENDING,
                FragmentStatus.COMPLETED, FragmentStatus.BLOCKCHAIN_SENT
        ):
            err_msg = ""

        elif status == FragmentStatus.FAILED:
            err_msg = (
                f"При попытке отправить звёзды fragment-api вернул статус FAILED, текст ошибки: {response['error']}"
            )

        else:
            err_msg = "fragment-api вернул неизвестный статус"

        return response, err_msg

    except Exception as exc:
        logger.exception(f"Error trying send stars:\n{exc.__class__.__name__} - {exc}")
        raise exc


async def safe_telegram_action_with_retries(
        celery_task: Task[P,TR],
        started_at: float,
        coro: Awaitable[CR],
        timeout: float | None = None,
        retries: int = -1,
        max_retries: int | None = None
) -> CR | BadRequest | str:
    """
    Если используется `max_retries`, то в параметрах исходной `celery_task` должен быть параметр `retries: int` (он
    начинается с 0).
    """

    if timeout is None:
        timeout = 900.0

    timeout_err = get_timeout_error_or_none(
        RetriesEntity.NETWORK_TIME, started_at, timeout,
        f"{coro.__qualname__}"
    )
    if timeout_err is not None:
        return str(timeout_err)

    retry_kwargs = cast(dict[str, object], celery_task.request.kwargs or {}).copy()  # noqa
    retry_kwargs["started_at"] = started_at

    if max_retries is not None:
        if retries >= 0:
            try:
                if retries >= max_retries:
                    err_msg = f"Превышено количество попыток ({max_retries}) для {coro.__qualname__}"
                    logger.exception(err_msg)
                    return err_msg
            except Exception as err:
                logger.exception(err)

        else:
            logger.exception(f"retries must be >= 0, now {retries}")

    try:
        return await coro

    except BadRequest as err:
        logger.debug(f"BadRequest when trying {coro.__qualname__}:\n{err = }")
        return err

    except RetryAfter as err:
        time_to_sleep = err.retry_after if isinstance(err.retry_after, int) else err.retry_after.total_seconds()
        raise celery_task.retry(
            exc=err,
            countdown=time_to_sleep + 1,
            kwargs=retry_kwargs
        )

    except (TimedOut, NetworkError, *SAFE_TO_RETRY) as err:
        min_countdown: float = 10.0
        max_countdown: float = 60.0
        jitter: float = 5.0

        if max_retries is not None and retries >= 0:
            _ = retry_kwargs.setdefault("retries", retries + 1)
        else:
            retries = celery_task.request.retries

        base_delay = min_countdown * (2.0 ** retries)
        base_delay = min(base_delay, max_countdown)
        jitter = random.uniform(0.0, jitter)
        countdown = base_delay + jitter

        if isinstance(err, TimedOut):
            err_msg = f"TimedOut while trying to await {coro.__qualname__}: retry after {countdown}s. Err: {err}"
        else:
            err_msg = f"NetworkError while trying to await {coro.__qualname__}: retry after {countdown}s. Err: {err}"
        logger.exception(err_msg)

        raise celery_task.retry(
            exc=err,
            countdown=countdown,
            kwargs=retry_kwargs
        )

    except Exception as err:
        err_msg = f"Error while trying to await {coro.__qualname__}:\n{err = }"
        logger.exception(err_msg)
        return err_msg


async def safe_notify_user_about_status_with_retries(
        celery_task: Task[P,R], started_at: float,
        bot: ExtBot[None], parse_mode: str,
        user_id: int, message_id: int,
        status: str, transaction_id: str,
        amount_stars: int, price: str,
        target_username: str,
        pay_url: str,
        promo_name: str = "", promo_discount: Decimal | None = None,
        *,
        timeout: float
) -> Message | bool | BadRequest | str:
    kwargs = cast(dict[str, object], celery_task.request.kwargs or {}).copy()  # noqa

    support_url = await safe_get_support_url_with_retries(
        celery_task, started_at, kwargs, 30.0, transaction_id
    )

    text, reply_markup, photo_name = await get_message_parts_for_status(
        cast(TransactionStatus, status), amount_stars, Decimal(price),
        target_username, user_id, transaction_id, pay_url,
        promo_name, promo_discount,
        support_url
    )
    async with bot:
        with create_media_source(photo_name) as media:
            return await safe_telegram_action_with_retries(
                celery_task, started_at,
                bot.edit_message_media(
                    media=InputMediaPhoto(media=media, caption=text, parse_mode=parse_mode),
                    chat_id=user_id,
                    message_id=message_id,
                    reply_markup=reply_markup
                ),
                timeout=timeout
            )
